In [1]:
import pandas as pd 
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree 
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score , roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split , GridSearchCV

In [2]:
data= pd.read_csv("Downloads/winequality-red.csv")

In [5]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [41]:
x= data.drop(columns='quality')

In [42]:
y= data.quality

In [43]:
x_train, x_test, y_train, y_test= train_test_split(x, y)

In [44]:
knn= KNeighborsClassifier()

In [45]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [46]:
knn.score(x_test, y_test)

0.485

In [54]:
param = {'n_neighbors':[3,5,7,9,12,13,15,17,21]
        }

In [48]:
grid_cv = GridSearchCV(knn, param_grid= param)

In [49]:
grid_cv.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 12, 13, 15, 17, 21]})

In [50]:
grid_cv.best_estimator_

KNeighborsClassifier(n_neighbors=17)

In [51]:
knn1=KNeighborsClassifier(n_neighbors=17)

In [52]:
knn1.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=17)

In [53]:
knn1.score(x_test, y_test)

0.515

In [73]:
param = {'n_neighbors':[3,5,7,9,12,13,15,17,21],
        'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],
        'leaf_size':[10, 15, 20, 15, 30, 35, 40, 45, 50],
         'p':[1,2],
         'weights':['uniform', 'distance']
        }

In [74]:
grid_cv1 = GridSearchCV(knn, param_grid= param)

In [75]:
grid_cv1.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 15, 20, 15, 30, 35, 40, 45, 50],
                         'n_neighbors': [3, 5, 7, 9, 12, 13, 15, 17, 21],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [65]:
grid_cv1.best_estimator_

KNeighborsClassifier(leaf_size=10, n_neighbors=21, weights='distance')

In [76]:
grid_cv1.best_params_

{'algorithm': 'auto',
 'leaf_size': 10,
 'n_neighbors': 21,
 'p': 2,
 'weights': 'distance'}

In [77]:
knn2=KNeighborsClassifier(algorithm= 'auto', n_neighbors=21, leaf_size=10, p=2, weights='distance')

In [78]:
knn2.fit(x_train, y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=21, weights='distance')

In [80]:
knn2.score(x_test, y_test)

0.5975

In [83]:
import pickle
pickle.dump(knn2, open('knn2.pkl', 'wb'))

In [84]:
pwd

'C:\\Users\\Abhijeet'

In [86]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 0896-6953

 Directory of C:\Users\Abhijeet

06-07-2022  15:08    <DIR>          .
06-07-2022  15:08    <DIR>          ..
13-05-2021  23:38    <DIR>          .anaconda
27-06-2022  16:20    <DIR>          .astropy
24-06-2022  17:23                19 .bash_history
06-07-2022  15:09    <DIR>          .conda
13-05-2021  23:38                43 .condarc
13-05-2021  23:56    <DIR>          .continuum
15-06-2022  03:26    <DIR>          .cufflinks
24-06-2022  17:54    <DIR>          .idea
05-07-2022  18:28    <DIR>          .ipynb_checkpoints
14-04-2021  03:02    <DIR>          .ipython
14-04-2021  03:21    <DIR>          .jupyter
14-04-2021  03:02    <DIR>          .matplotlib
03-05-2021  00:12    <DIR>          .streamlit
14-05-2021  19:34    <DIR>          .vscode
27-06-2022  15:23               216 _netrc
08-05-2021  21:20    <DIR>          3D Objects
23-06-2022  00:01               571 adminssion_lr_model.pickle
03-05-2021  01:02  

In [89]:
knn2.predict(x_test)

array([6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 7, 5, 5, 5, 6,
       7, 6, 6, 5, 6, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 7,
       5, 6, 5, 7, 6, 5, 6, 5, 5, 6, 5, 6, 7, 5, 5, 5, 5, 6, 6, 6, 6, 6,
       5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 5, 5, 7, 7, 6, 6, 6, 5, 6, 5,
       6, 5, 6, 6, 7, 6, 5, 6, 5, 5, 5, 5, 6, 5, 6, 7, 5, 5, 5, 5, 6, 6,
       5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 6, 6, 6, 6, 5, 5,
       6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 6, 6, 5,
       6, 5, 6, 7, 6, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 5, 7, 5, 6, 5, 5, 5,
       5, 7, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5,
       6, 5, 5, 5, 7, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 5,
       5, 5, 5, 6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 5, 7, 6, 5, 5, 5, 6, 5, 5,
       6, 5, 6, 6, 5, 5, 6, 6, 5, 6, 7, 6, 6, 5, 6, 6, 6, 6, 5, 5, 6, 5,
       5, 5, 6, 6, 5, 6, 7, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6,
       6, 6, 5, 6, 5, 7, 6, 5, 5, 5, 7, 5, 6, 6, 6,

In [91]:
knn2.predict([x_test.iloc[1]])

C:\Users\Abhijeet\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([5], dtype=int64)

In [92]:
x_test.iloc[1]

fixed acidity             5.90000
volatile acidity          0.29000
citric acid               0.25000
residual sugar           13.40000
chlorides                 0.06700
free sulfur dioxide      72.00000
total sulfur dioxide    160.00000
density                   0.99721
pH                        3.33000
sulphates                 0.54000
alcohol                  10.30000
Name: 1244, dtype: float64

In [ ]:
#SVM

In [60]:
from sklearn.svm import SVC

In [61]:
svc = SVC()

In [95]:
svc.fit(x_train, y_train)

SVC()

In [99]:
svc.score(x_test, y_test)

0.4925

In [126]:
param1= {"kernel": ['linear', 'poly', 'rbf', 'sigmoid'],
        "C":[0.1, 1, 10, 100, 1000],
        "gamma":[0.001, 0.01,0.1,0.4,0.8]}

In [ ]:
svm_grid= GridSearchCV(estimator=svc, param_grid=param1, verbose=3)
svm_grid.fit(x_train, y_train)

In [104]:
svm_grid.best_params_

{'kernel': 'linear'}

In [119]:
svc_grid=SVC(kernel='linear',C=1)

In [120]:
svc_grid.fit(x_train, y_train)

SVC(C=1, kernel='linear')

In [121]:
svc_grid.score(x_test, y_test)

0.6325

In [ ]:
#SVR:

In [21]:
df= pd.read_csv("E:\\iNeuron -FSDS\\76. Machine Learning\\Linear Regression- Part 1\\Admission_Prediction.csv")

In [22]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [36]:
x= df.drop(['Serial No.','Chance of Admit'], axis= 1)

In [37]:
y= df['Chance of Admit']

In [38]:
x_train, x_test, y_train, y_test= train_test_split(x, y, random_state=30, test_size=0.20)

In [39]:
from sklearn.svm import SVR

In [40]:
svr=SVR()

In [41]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [33]:
df['GRE Score']=df['GRE Score'].fillna(df['GRE Score'].mean())
df['TOEFL Score']=df['TOEFL Score'].fillna(df['TOEFL Score'].mean())
df['University Rating']=df['University Rating'].fillna(df['University Rating'].mean())

In [34]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [42]:
svr.fit(x_train, y_train)

SVR()

In [43]:
svr.score(x_test, y_test)

0.6774861142346674

In [48]:
svr.predict([[327.0, 113.0, 4.0, 4.5, 4.5, 9.04, 0]])

C:\Users\Abhijeet\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([0.8091213])

In [49]:
 svr.score(x_train, y_train)

0.6662794259565514

In [51]:
from sklearn.metrics import r2_score

In [54]:
r2_score(y_test, svr.predict(x_test))

0.6774861142346674

In [58]:
svr.predict([x.iloc[0]])

C:\Users\Abhijeet\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([0.89252382])

In [59]:
y[0]

0.92

In [ ]:
#svr.score() & svc.score(): Both are different, just tap (shift+tab)

# Stacking:

In [62]:
import pandas as pd 
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree 
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score , roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [63]:
df= pd.read_csv("Downloads/winequality-red.csv")

In [64]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [66]:
x= df.drop(columns= 'quality')
y= df.quality

In [71]:
train , val_train , test , val_test  = train_test_split(x,y,test_size = .50 , random_state = 30)

In [72]:
x_train, x_test, y_train, y_test= train_test_split(x,y, random_state= 30, test_size=0.15)

In [73]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [74]:
knn.score(x_test,y_test)

0.5083333333333333

In [75]:
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [76]:
svc.score(x_test,y_test)

0.5125

In [77]:
predcition_knn = knn.predict(val_train)
prediction_svc = svc.predict(val_train)

In [78]:
predcition_knn

array([7, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6, 7, 6, 5, 6, 5, 5, 5, 6,
       5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 5, 6, 5, 4,
       6, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5,
       5, 6, 5, 4, 5, 5, 5, 5, 6, 6, 7, 5, 5, 6, 6, 7, 6, 5, 5, 5, 5, 6,
       5, 5, 6, 6, 5, 6, 6, 7, 5, 7, 5, 7, 6, 5, 5, 7, 6, 6, 6, 5, 5, 5,
       5, 5, 5, 6, 7, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5,
       5, 5, 7, 5, 5, 5, 6, 7, 7, 5, 5, 5, 6, 5, 5, 5, 5, 7, 5, 5, 5, 6,
       5, 7, 6, 7, 7, 5, 5, 6, 6, 5, 6, 5, 5, 6, 7, 6, 6, 6, 5, 6, 5, 5,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5, 7, 6, 6, 5, 5, 6, 5, 7, 5, 6, 5,
       5, 6, 6, 6, 6, 5, 5, 6, 7, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 7, 5,
       6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5, 6,
       5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 6, 6,
       4, 5, 6, 6, 6, 6, 5, 5, 6, 6, 5, 6, 4, 6, 5, 6, 5, 5, 5, 6, 5, 6,
       7, 6, 5, 7, 5, 5, 6, 7, 5, 6, 5, 6, 5, 6, 5,

In [79]:
prediction_svc

array([6, 6, 6, 5, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6,
       6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 6, 5, 5,
       5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6,
       5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5,
       6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5,

In [80]:
input3 = np.column_stack((predcition_knn,prediction_svc))

In [81]:
output = val_test

In [82]:
pd.DataFrame(input3)

0  1
0    7  6
1    5  6
2    6  6
3    5  5
4    5  6
..  .. ..
795  5  6
796  5  6
797  6  5
798  6  6
799  6  5

[800 rows x 2 columns]

In [83]:
rf = RandomForestClassifier()

In [84]:
rf.fit(input3,output)

RandomForestClassifier()

In [85]:
rf.score(x_test,y_test)

C:\Users\Abhijeet\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


ValueError: X has 11 features, but RandomForestClassifier is expecting 2 features as input.

In [86]:
knn_output = knn.predict(x_test)
svc_output = svc.predict(x_test)

In [87]:
output_stack1 = np.column_stack ((knn_output,svc_output))

In [88]:
rf.predict(output_stack1)

array([7, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6, 7, 6, 5, 6, 5, 5, 5, 6,
       5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 5, 6, 5, 6,
       6, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5,
       5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 7, 5, 5, 6, 6, 7, 6, 5, 5, 5, 5, 6,
       5, 5, 6, 6, 5, 6, 6, 7, 5, 7, 5, 7, 6, 5, 5, 7, 6, 6, 6, 5, 5, 5,
       5, 5, 5, 6, 7, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5,
       5, 5, 7, 5, 5, 5, 6, 7, 7, 5, 5, 5, 6, 5, 5, 5, 5, 7, 5, 5, 5, 6,
       5, 7, 6, 7, 7, 5, 5, 6, 6, 5, 6, 5, 5, 6, 7, 6, 6, 6, 5, 6, 5, 5,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5, 7, 6, 6, 5, 5, 6, 5, 7, 5, 6, 5,
       5, 6, 6, 6, 6, 5, 5, 6, 7, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 7, 5,
       6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6],
      dtype=int64)

In [89]:
rf.score(output_stack1 , y_test)

0.5125